server:
  port: 8001

spring:
  config:
    import: optional:classpath:/application.dev.yaml
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  data:
    redis:
      host: 192.168.101.65
      port: 6379
      password: redis
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  domain:
    default: b23.link:8001
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml