server:
  port: 8001

spring:
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  data:
    redis:
      host: 192.168.101.65
      port: 6379
      password: redis