server:
  port: 8001

spring:
  application:
    name: short-link-project
  config:
    import: optional:classpath:/application.dev.yaml
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  data:
    redis:
      host: 192.168.101.65
      port: 6379
      password: redis
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
short-link:
  domain:
    default: b23.link:8001
  goto-domain:
    white-list:
      enable: true
      names: '哔哩哔哩,Google,Github'
      details:
        - bilibili.com
        - google.com
        - github.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg